# Colab notebook or tutorial
### [How to run PyTorch with GPU and CUDA 9.2 support on Google Colab](https://www.dlology.com/blog/how-to-run-pytorch-with-gpu-and-cuda-92-support-on-google-colab/)

In [1]:
!python --version

Python 3.6.6


In [2]:
!cat /etc/*-release

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic


## Install [Cuda 9.2](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1710&target_type=deblocal)

In [3]:
!wget https://developer.nvidia.com/compute/cuda/9.2/Prod2/local_installers/cuda-repo-ubuntu1710-9-2-local_9.2.148-1_amd64

--2018-11-16 21:47:46--  https://developer.nvidia.com/compute/cuda/9.2/Prod2/local_installers/cuda-repo-ubuntu1710-9-2-local_9.2.148-1_amd64
Resolving developer.nvidia.com (developer.nvidia.com)... 192.229.182.215
Connecting to developer.nvidia.com (developer.nvidia.com)|192.229.182.215|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://developer.download.nvidia.com/compute/cuda/9.2/secure/Prod2/local_installers/cuda-repo-ubuntu1710-9-2-local_9.2.148-1_amd64.deb?gcku6v7x8s36sBbLUQEXSujqZwpCXOcNa_NZuFM_tQ0PZpO9rp0p_t0RRRzFDGxvUMAS9xw8y7O9npzapMsvs0BwS5WzATYluQE8jLtPHrmNQqeEYKAR_HFXzY7NoyIlPCiP3drUOebezyXtm_AFBVSiuiMHTh_8ZVZRr4LSGvvhRYz9ArSCdYOG3kDeOuGqe2IbXYBNhShsjeyMduKR2g [following]
--2018-11-16 21:47:47--  https://developer.download.nvidia.com/compute/cuda/9.2/secure/Prod2/local_installers/cuda-repo-ubuntu1710-9-2-local_9.2.148-1_amd64.deb?gcku6v7x8s36sBbLUQEXSujqZwpCXOcNa_NZuFM_tQ0PZpO9rp0p_t0RRRzFDGxvUMAS9xw8y7O9npzapMsvs0BwS5WzATYluQE8jLtPHrmNQ

In [4]:
!ls

cuda-repo-ubuntu1710-9-2-local_9.2.148-1_amd64	sample_data


In [5]:
!dpkg -i cuda-repo-ubuntu1710-9-2-local_9.2.148-1_amd64

Selecting previously unselected package cuda-repo-ubuntu1710-9-2-local.
(Reading database ... 22280 files and directories currently installed.)
Preparing to unpack cuda-repo-ubuntu1710-9-2-local_9.2.148-1_amd64 ...
Unpacking cuda-repo-ubuntu1710-9-2-local (9.2.148-1) ...
Setting up cuda-repo-ubuntu1710-9-2-local (9.2.148-1) ...


In [6]:
!ls /var/ | grep cuda-repo

cuda-repo-9-2-local


In [7]:
!apt-key add /var/cuda-repo-9-2-local/7fa2af80.pub

OK


In [8]:
!apt-get update

Get:1 file:/var/cuda-repo-9-2-local  InRelease
Ign:1 file:/var/cuda-repo-9-2-local  InRelease
Get:2 file:/var/cuda-repo-9-2-local  Release [574 B]
Get:2 file:/var/cuda-repo-9-2-local  Release [574 B]
Get:3 file:/var/cuda-repo-9-2-local  Release.gpg [801 B]
Get:3 file:/var/cuda-repo-9-2-local  Release.gpg [801 B]
Get:4 http://security.ubuntu.com/ubuntu bionic-security InRelease [83.2 kB]
Hit:5 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu bionic InRelease
Hit:6 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:7 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:8 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Ign:9 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1710/x86_64  InRelease
Get:10 file:/var/cuda-repo-9-2-local  Packages [18.8 kB]
Ign:11 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64  InRelease
Hit:12 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1710

In [9]:
!apt-get install cuda

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  acpid adwaita-icon-theme at-spi2-core ca-certificates-java cuda-9-2
  cuda-compiler-9-2 cuda-cublas-dev-9-2 cuda-cufft-dev-9-2 cuda-curand-dev-9-2
  cuda-cusolver-dev-9-2 cuda-cusparse-dev-9-2 cuda-demo-suite-9-2
  cuda-documentation-9-2 cuda-drivers cuda-libraries-dev-9-2 cuda-npp-dev-9-2
  cuda-nsight-9-2 cuda-nvgraph-dev-9-2 cuda-nvml-dev-9-2 cuda-nvprune-9-2
  cuda-nvrtc-dev-9-2 cuda-nvvp-9-2 cuda-runtime-9-2 cuda-samples-9-2
  cuda-toolkit-9-2 cuda-tools-9-2 cuda-visual-tools-9-2 dbus
  dconf-gsettings-backend dconf-service default-jre default-jre-headless dkms
  dmsetup fakeroot fontconfig fonts-dejavu-core fonts-dejavu-extra freeglut3
  freeglut3-dev glib-networking glib-networking-common
  glib-networking-services gsettings-desktop-schemas gtk-update-icon-cache
  hicolor-icon-theme humanity-icon-theme java-common keyboard-configu

## Install [PyTorch](https://pytorch.org/) with Cuda 9.2 support

In [10]:
!pip install http://download.pytorch.org/whl/cu92/torch-0.4.1-cp36-cp36m-linux_x86_64.whl 
!pip install torchvision

    100% |████████████████████████████████| 512.6MB 53.7MB/s 
tcmalloc: large alloc 1073750016 bytes == 0x57b92000 @  0x7fd8c2d512a4 0x594e17 0x626104 0x51190a 0x4f5277 0x510c78 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f6070 0x510c78 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f6070 0x4f3338 0x510fb0 0x5119bd 0x4f6070
    100% |████████████████████████████████| 61kB 4.4MB/s 
    100% |████████████████████████████████| 2.0MB 10.5MB/s 
  Found existing installation: Pillow 4.0.0
    Uninstalling Pillow-4.0.0:
      Successfully uninstalled Pillow-4.0.0


In [11]:
import torch
import torch.autograd as autograd
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

In [16]:
# torch.tensor(data) creates a torch.Tensor object with the given data.
V_data = [1., 2., 3.]
V = torch.tensor(V_data)
print('V:', V)

print()

# Creates a matrix
M_data = [[1., 2., 3.],
          [4., 5., 6.]]
M = torch.tensor(M_data)
print('M:', M)

print()

# Create a 3D tensor of size 2x2x2.
T_data = [[[1., 2.], [3., 4.]],
          [[5., 6.], [7., 8.]]]
T = torch.tensor(T_data)
print('T:', T)

V: tensor([1., 2., 3.])

M: tensor([[1., 2., 3.],
        [4., 5., 6.]])

T: tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


In [17]:
# Index into V and get a scalar (0 dimensional tensor)
print(V[0])
# Get a Python number from it
print(V[0].item())

# Index into M and get a vector
print(M[0])

# Index into T and get a matrix
print(T[0])

tensor(1.)
1.0
tensor([1., 2., 3.])
tensor([[1., 2.],
        [3., 4.]])


In [18]:
x = torch.randn((3, 4, 5))
print(x)

tensor([[[-1.5256, -0.7502, -0.6540, -1.6095, -0.1002],
         [-0.6092, -0.9798, -1.6091, -0.7121,  0.3037],
         [-0.7773, -0.2515, -0.2223,  1.6871,  0.2284],
         [ 0.4676, -0.6970, -1.1608,  0.6995,  0.1991]],

        [[ 0.8657,  0.2444, -0.6629,  0.8073,  1.1017],
         [-0.1759, -2.2456, -1.4465,  0.0612, -0.6177],
         [-0.7981, -0.1316,  1.8793, -0.0721,  0.1578],
         [-0.7735,  0.1991,  0.0457,  0.1530, -0.4757]],

        [[-0.1110,  0.2927, -0.1578, -0.0288,  0.4533],
         [ 1.1422,  0.2486, -1.7754, -0.0255, -1.0233],
         [-0.5962, -1.0055,  0.4285,  1.4761, -1.7869],
         [ 1.6103, -0.7040, -0.1853, -0.9962, -0.8313]]])


In [19]:
x = torch.tensor([1., 2., 3.])
y = torch.tensor([4., 5., 6.])
z = x + y
print(z)

tensor([5., 7., 9.])


In [22]:
# By default, it concatenates along the first axis (concatenates rows)
x_1 = torch.randn(2, 5)
y_1 = torch.randn(3, 5)
z_1 = torch.cat([x_1, y_1])
print(z_1)

tensor([[-1.6476,  0.8098,  0.0554,  1.1340, -0.5326],
        [ 0.6592, -1.5964, -0.3769, -3.1020, -0.0995],
        [-0.7213,  1.2708, -0.0020, -1.0952,  0.6016],
        [ 0.6984, -0.8005,  1.5381,  1.4673,  1.5951],
        [-1.5279,  1.0156, -0.2020, -1.2865,  0.8231]])


In [25]:
# Concatenate columns:
x_2 = torch.randn(2, 3)
y_2 = torch.randn(2, 5)
# second arg specifies which axis to concat along
z_2 = torch.cat([x_2, y_2], 1)
print(z_2)

tensor([[ 0.5652, -0.0115,  0.6706,  1.6169, -0.9026,  0.1737,  0.0772, -0.9339],
        [-0.4929,  1.5050, -2.3264,  0.0914,  1.3940, -0.6877, -0.5058,  0.1924]])


In [29]:
lin = nn.Linear(5, 3)  # maps from R^5 to R^3, parameters A, b
# data is 2x5.  A maps from 5 to 3... can we map "data" under A?

data = torch.randn(2, 5)
print(lin(data))  # yes

tensor([[-0.3854, -0.3481, -0.6645],
        [ 1.0513,  0.0965,  0.8867]], grad_fn=<ThAddmmBackward>)


In [42]:
# Is a sentence English or Spanish?
data = [("me gusta comer en la cafeteria".split(), "SPANISH"),
        ("Give it to me".split(), "ENGLISH"),
        ("Yo that is not a good idea".split(), "ENGLISH"),
        ("I like to sing la la la in the cafeteria".split(), "ENGLISH"),
        ("No creo que sea una buena idea".split(), "SPANISH"),
        ("No it is not a good idea to get lost at sea".split(), "ENGLISH")]

test_data = [("Yo creo que si".split(), "SPANISH"),
             ("it is lost on me".split(), "ENGLISH")]

# word_to_ix maps each word in the vocab to a unique integer, which will be its
# index into the Bag of words vector
word_to_ix = {}
for sent, _ in data + test_data:
    for word in sent:
        if word.lower() not in word_to_ix:
            # clever -- use the len of the dictionary!
            word_to_ix[word.lower()] = len(word_to_ix)
            
word_to_ix

{'a': 13,
 'at': 29,
 'buena': 26,
 'cafeteria': 5,
 'comer': 2,
 'creo': 22,
 'en': 3,
 'get': 27,
 'give': 6,
 'good': 14,
 'gusta': 1,
 'i': 16,
 'idea': 15,
 'in': 19,
 'is': 11,
 'it': 7,
 'la': 4,
 'like': 17,
 'lost': 28,
 'me': 0,
 'no': 21,
 'not': 12,
 'on': 31,
 'que': 23,
 'sea': 24,
 'si': 30,
 'sing': 18,
 'that': 10,
 'the': 20,
 'to': 8,
 'una': 25,
 'yo': 9}

In [0]:
VOCAB_SIZE = len(word_to_ix)
NUM_LABELS = 2

class BoWClassifier(nn.Module):  # inheriting from nn.Module!

    def __init__(self, num_labels, vocab_size):
        # calls the init function of nn.Module.  Dont get confused by syntax,
        # just always do it in an nn.Module
        super(BoWClassifier, self).__init__()

        # Define the parameters that you will need.  In this case, we need A and b,
        # the parameters of the affine mapping.
        # Torch defines nn.Linear(), which provides the affine map.
        # Make sure you understand why the input dimension is vocab_size
        # and the output is num_labels!
        self.linear = nn.Linear(vocab_size, num_labels)

        # NOTE! The non-linearity log softmax does not have parameters! So we don't need
        # to worry about that here

    def forward(self, bow_vec):
        # Pass the input through the linear layer,
        # then pass that through log_softmax.
        # Many non-linearities and other functions are in torch.nn.functional
        return F.log_softmax(self.linear(bow_vec), dim=1)

In [0]:
def make_bow_vector(sentence, word_to_ix):
    vec = torch.zeros(len(word_to_ix))
    for word in sentence:
        vec[word_to_ix[word]] += 1
    return vec.view(1, -1)


def make_target(label, label_to_ix):
    return torch.LongTensor([label_to_ix[label]])


model = BoWClassifier(NUM_LABELS, VOCAB_SIZE)

In [46]:
# the model knows its parameters.  The first output below is A, the second is b.
# Whenever you assign a component to a class variable in the __init__ function
# of a module, which was done with the line
# self.linear = nn.Linear(...)
# Then through some Python magic from the PyTorch devs, your module
# (in this case, BoWClassifier) will store knowledge of the nn.Linear's parameters
for param in model.parameters():
    print(param)

# To run the model, pass in a BoW vector
# Here we don't need to train, so the code is wrapped in torch.no_grad()
with torch.no_grad():
    sample = data[0]
    bow_vector = make_bow_vector(sample[0], word_to_ix)
    log_probs = model(bow_vector)
    print(log_probs)

Parameter containing:
tensor([[-0.1767, -0.0059, -0.0563, -0.1120,  0.0293,  0.0072,  0.0270, -0.0989,
         -0.1732,  0.0039, -0.0721, -0.0596,  0.1301,  0.0289,  0.0807, -0.0494,
         -0.1403,  0.0352, -0.1171,  0.0219, -0.1380,  0.1333, -0.1204,  0.1535,
          0.1249,  0.1336,  0.1061,  0.0409, -0.0086, -0.0028, -0.0703, -0.1625],
        [ 0.1611,  0.0092,  0.0831,  0.0065,  0.0508, -0.1089, -0.1374,  0.1348,
          0.0670,  0.0873, -0.1755,  0.0120, -0.1649, -0.0202, -0.0093, -0.1244,
         -0.1750,  0.0012,  0.1590,  0.1593, -0.1076, -0.0314, -0.1478, -0.1381,
         -0.0485,  0.1716, -0.0461,  0.0102,  0.1663,  0.0315,  0.1426,  0.1175]],
       requires_grad=True)
Parameter containing:
tensor([0.1658, 0.0303], requires_grad=True)
tensor([[-0.9015, -0.5208]])


In [0]:
from time import sleep

In [52]:
for i in range(1000):
  j = 1 + 1
  sleep(20)

KeyboardInterrupt: ignored